//! Cross-language golden fixture for the beacon v2 presence record (ADDR-1).
//!
//! The fixture at `tests/fixtures/beacon/presence_v2.json` was generated by
//! the **Python** signer (`forgewire_fabric.hub._crypto.sign_payload`) over
//! the canonical record bytes. This test proves the Rust side reproduces the
//! same canonical bytes and the same deterministic ed25519 signature, and
//! verifies the Python-made signature — byte parity across languages, the
//! same discipline as the dispatch-envelope and audit-chain fixtures.

use std::path::PathBuf;

use fabric_beacon::{canonical_presence_bytes, PresenceRecord};

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures/beacon/presence_v2.json")
}

#[test]
fn python_generated_fixture_verifies_in_rust() {
    let raw = std::fs::read_to_string(fixture_path())
        .expect("fixture missing: tests/fixtures/beacon/presence_v2.json");
    let fixture: serde_json::Value = serde_json::from_str(&raw).unwrap();

    let sk = fixture["secret_key_hex"].as_str().unwrap();
    let expected_canonical = fixture["canonical"].as_str().unwrap();
    let expected_sig = fixture["sig"].as_str().unwrap();

    // Reconstruct the record with the fixture's signature attached.
    let mut record_value = fixture["record_without_sig"].clone();
    record_value["sig"] = serde_json::Value::String(expected_sig.to_owned());
    let record: PresenceRecord = serde_json::from_value(record_value).unwrap();

    // 1. Rust canonicalization reproduces the Python canonical bytes.
    let canon = canonical_presence_bytes(&record).unwrap();
    assert_eq!(
        String::from_utf8(canon.clone()).unwrap(),
        expected_canonical,
        "Rust canonical bytes diverge from the Python-generated fixture"
    );

    // 2. The Python-made signature verifies under the Rust verifier.
    assert!(
        record.signature_valid(),
        "Python signature failed Rust verification"
    );

    // 3. RFC 8032 ed25519 is deterministic: Rust signing the same bytes with
    //    the same key must produce the identical signature hex.
    let rust_sig = fabric_protocol::sign_payload_hex(sk, &canon).unwrap();
    assert_eq!(
        rust_sig, expected_sig,
        "Rust signature differs from Python signature over identical bytes"
    );
}
