"""Beacon v2: signed full-node presence — Python parity client (ADDR-1).

Parity implementation of ``crates/fabric-beacon/src/presence.rs``. See
``work/active/114-forgewire-fabric/README.md`` (dhcp-proof-addressing design in git history) and
``tests/fixtures/beacon/presence_v2.json`` for the cross-language golden
fixture (generated by this module's signer, verified by the Rust verifier,
and vice versa — ed25519 is deterministic, so signatures must byte-match).

Model recap:

* The record never contains an IP — receivers use the datagram source
  address, which is what makes presence DHCP-proof.
* A record's signature (over the canonical sorted-key JSON of every field
  except ``sig``) proves *key possession by the sender*. Mapping that key to
  cluster trust is the caller's job (hub registry / join-token bootstrap).
* Broadcast announces are advisory and freshness-windowed. The query path is
  replay-proof: queries carry a random ``nonce`` that signed responses must
  echo inside the signature.
* On broadcast-hostile media (the reference adversarial network is a phone
  WiFi hotspot) use :func:`collect_presence_addrs` with last-known-good
  unicast targets from the node directory.
"""

from __future__ import annotations

import json
import logging
import socket
import threading
import time as _time
from dataclasses import dataclass, field
from typing import Any

from ._crypto import sign_payload, verify_signature

LOGGER = logging.getLogger("forgewire_fabric.presence")

PRESENCE_MAGIC = "FWBEACON"
PRESENCE_VERSION = 2
#: Distinct from the v1 hub-discovery port (48765): on combined hub+runner
#: hosts the hub owns that bind.
PRESENCE_PORT = 48766
ROLE_NODE = "node"
ROLE_NODE_QUERY = "node-query"
PRESENCE_FRESH_SECS = 300

_MAX_DATAGRAM = 2048


def canonical_presence_bytes(record: dict[str, Any]) -> bytes:
    """Canonical signing bytes: sorted-key compact JSON of all fields but ``sig``.

    Byte-identical to ``fabric_protocol::canonicalize`` on the Rust side —
    pinned by the golden fixture test.
    """
    body = {k: v for k, v in record.items() if k != "sig"}
    return json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def build_presence_record(
    *,
    node_id: str,
    hostname: str,
    services: dict[str, int],
    token_hash: str,
    public_key_hex: str,
    secret_key_hex: str,
    nonce: str = "",
    ts: int | None = None,
) -> dict[str, Any]:
    """Build and sign a presence record (optionally echoing a query nonce)."""
    record: dict[str, Any] = {
        "magic": PRESENCE_MAGIC,
        "v": PRESENCE_VERSION,
        "role": ROLE_NODE,
        "node_id": node_id,
        "hostname": hostname,
        "services": dict(sorted(services.items())),
        "ts": int(ts if ts is not None else _time.time()),
        "token_hash": token_hash,
        "nonce": nonce,
        "public_key_hex": public_key_hex,
        "sig": "",
    }
    record["sig"] = sign_payload(secret_key_hex, canonical_presence_bytes(record))
    return record


def signature_valid(record: dict[str, Any]) -> bool:
    """Verify the embedded signature against the embedded public key.

    Proves key possession by the sender — NOT cluster membership (compare
    ``public_key_hex`` against the hub registry for that).
    """
    try:
        return verify_signature(
            record["public_key_hex"],
            canonical_presence_bytes(record),
            record["sig"],
        )
    except Exception:
        return False


def is_fresh(record: dict[str, Any], now: float | None = None) -> bool:
    """Freshness check for unsolicited announces (clock-skew tolerant)."""
    now_s = int(now if now is not None else _time.time())
    ts = int(record.get("ts", 0))
    return abs(now_s - ts) <= PRESENCE_FRESH_SECS


def _is_presence(record: dict[str, Any]) -> bool:
    return (
        record.get("magic") == PRESENCE_MAGIC
        and record.get("v") == PRESENCE_VERSION
        and record.get("role") == ROLE_NODE
        and bool(record.get("node_id"))
        and bool(record.get("sig"))
    )


@dataclass(slots=True)
class ObservedPresence:
    """A presence record observed on the wire."""

    record: dict[str, Any]
    source: str
    sig_valid: bool


def collect_presence_addrs(
    targets: list[tuple[str, int]],
    timeout: float = 1.5,
    want_token_hash: str = "",
    nonce: str = "",
) -> list[ObservedPresence]:
    """Query explicit unicast/broadcast ``targets`` for presence records.

    This is the broadcast-hostile-media path: pass last-known-good addresses
    from the node directory when broadcast yields nothing. Responses that do
    not echo ``nonce`` are dropped, so a fresh random nonce makes the
    collection replay-proof.
    """
    query = json.dumps(
        {
            "magic": PRESENCE_MAGIC,
            "v": PRESENCE_VERSION,
            "role": ROLE_NODE_QUERY,
            "nonce": nonce,
            "token_hash": want_token_hash,
        }
    ).encode()

    found: dict[str, ObservedPresence] = {}
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        sock.settimeout(0.1)
        sock.bind(("", 0))

        def send_query() -> None:
            for t in targets:
                try:
                    sock.sendto(query, t)
                except OSError:
                    pass

        send_query()
        deadline = _time.monotonic() + timeout
        last_query = _time.monotonic()
        while _time.monotonic() < deadline:
            if _time.monotonic() - last_query >= 0.6:
                send_query()
                last_query = _time.monotonic()
            try:
                data, (src_ip, _) = sock.recvfrom(_MAX_DATAGRAM)
            except socket.timeout:
                continue
            try:
                rec = json.loads(data.decode("utf-8"))
            except Exception:
                continue
            if not isinstance(rec, dict) or not _is_presence(rec):
                continue
            if rec.get("nonce", "") != nonce:
                continue  # stale or replayed response
            if want_token_hash and rec.get("token_hash") and rec["token_hash"] != want_token_hash:
                continue
            node_id = rec["node_id"]
            if node_id not in found:
                found[node_id] = ObservedPresence(
                    record=rec, source=src_ip, sig_valid=signature_valid(rec)
                )
        sock.close()
    except OSError as exc:
        LOGGER.debug("presence collection failed: %s", exc)
    return list(found.values())


def collect_presence(
    port: int = PRESENCE_PORT,
    timeout: float = 1.5,
    want_token_hash: str = "",
    nonce: str = "",
) -> list[ObservedPresence]:
    """Collect presence via LAN broadcast. On broadcast-hostile media use
    :func:`collect_presence_addrs` with directory addresses instead."""
    return collect_presence_addrs(
        [("255.255.255.255", port)], timeout, want_token_hash, nonce
    )


@dataclass(slots=True)
class PresenceResponder:
    """Threaded presence responder (announce + nonce-echoing query replies).

    Python-hosted parity of the Rust ``serve_presence``; used by tests and by
    Python-hosted nodes. ``stop()`` for clean teardown.
    """

    node_id: str
    hostname: str
    services: dict[str, int]
    token_hash: str
    public_key_hex: str
    secret_key_hex: str
    port: int = PRESENCE_PORT
    announce_interval: float = 15.0
    _stop: threading.Event = field(default_factory=threading.Event)
    _thread: threading.Thread | None = None

    def _record(self, nonce: str = "") -> dict[str, Any]:
        return build_presence_record(
            node_id=self.node_id,
            hostname=self.hostname,
            services=self.services,
            token_hash=self.token_hash,
            public_key_hex=self.public_key_hex,
            secret_key_hex=self.secret_key_hex,
            nonce=nonce,
        )

    def _run(self) -> None:
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            sock.settimeout(0.5)
            sock.bind(("", self.port))
        except OSError as exc:
            LOGGER.warning("presence responder unavailable (continuing without): %s", exc)
            return
        last_announce = 0.0
        while not self._stop.is_set():
            now = _time.monotonic()
            if now - last_announce >= self.announce_interval:
                try:
                    payload = json.dumps(self._record()).encode()
                    sock.sendto(payload, ("255.255.255.255", self.port))
                except OSError:
                    pass
                last_announce = now
            try:
                data, src = sock.recvfrom(_MAX_DATAGRAM)
            except socket.timeout:
                continue
            except OSError:
                continue
            try:
                q = json.loads(data.decode("utf-8"))
            except Exception:
                continue
            if (
                not isinstance(q, dict)
                or q.get("magic") != PRESENCE_MAGIC
                or q.get("v") != PRESENCE_VERSION
                or q.get("role") != ROLE_NODE_QUERY
            ):
                continue
            want = q.get("token_hash", "")
            if want and want != self.token_hash:
                continue
            try:
                reply = json.dumps(self._record(nonce=q.get("nonce", ""))).encode()
                sock.sendto(reply, src)
            except OSError:
                pass
        sock.close()

    def start(self) -> "PresenceResponder":
        self._thread = threading.Thread(target=self._run, daemon=True, name="fw-presence")
        self._thread.start()
        return self

    def stop(self) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=2.0)
